name: SaveMeBackup
main: com.osher.minecraft.undo.UndoPlugin
version: 1.1
commands:
   savemebackup:
      description: Run Backup
      usage: /savemebackup hourly|daily
      permission: SaveMeBackup.Save
      permission-message: You don't have backup permission

permissions:
   SaveMeBackup.Save:
      description: Run backup on demand
      default: op
